import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { callLLM } from '../src/llm-client.js';
import { generateResumePdf, generateCoverLetterPdf } from '../src/pdf-generator.js';
import type { ResumeData } from '../src/types.js';

describe('JobPulse AI — Multi-Provider LLM Client & Career Tools', () => {
  const originalEnv = { ...process.env };

  beforeEach(() => {
    process.env = { ...originalEnv };
    delete process.env['GEMINI_API_KEY'];
    delete process.env['NEXT_PUBLIC_GEMINI_API_KEY'];
    delete process.env['GROQ_API_KEY'];
    delete process.env['DEEPSEEK_API_KEY'];
    delete process.env['OPENAI_API_KEY'];
  });

  afterEach(() => {
    process.env = originalEnv;
  });

  it('Test 1: Zero-config fallback returns high-quality mock resume JSON in jsonMode', async () => {
    const res = await callLLM({
      userPrompt: 'TARGET ROLE: Staff Infrastructure Engineer\nTARGET COMPANY: Datadog\nName: Jordan Vance',
      jsonMode: true,
    });

    expect(res.provider).toBe('mock');
    expect(res.model).toBe('built-in-template');

    const parsed = JSON.parse(res.content) as ResumeData;
    expect(parsed.atsScore).toBeGreaterThanOrEqual(85);
    expect(parsed.candidate?.name).toBe('Jordan Vance');
    expect(parsed.summary).toContain('Staff Infrastructure Engineer');
    expect(parsed.summary).toContain('Datadog');
    expect(parsed.experience?.length).toBeGreaterThan(0);
    expect(parsed.skills?.languages?.length).toBeGreaterThan(0);
  });

  it('Test 2: Zero-config fallback returns cover letter text for cover letter prompt', async () => {
    const res = await callLLM({
      userPrompt: 'JOB TITLE: Lead Backend Engineer\nCOMPANY: Stripe\nPlease write a cover letter.',
      jsonMode: false,
    });

    expect(res.provider).toBe('mock');
    expect(res.content).toContain('Dear Hiring Team at Stripe');
    expect(res.content).toContain('Lead Backend Engineer');
  });

  it('Test 3: Zero-config fallback returns interview answer for screening question prompt', async () => {
    const res = await callLLM({
      userPrompt: 'APPLICATION QUESTION: Why are you a good fit for this role?\nJOB TITLE: Cloud Architect',
      jsonMode: false,
    });

    expect(res.provider).toBe('mock');
    expect(res.content.length).toBeGreaterThan(50);
  });

  it('Test 4: Successfully calls Gemini when GEMINI_API_KEY is configured', async () => {
    process.env['GEMINI_API_KEY'] = 'test-gemini-key-123';

    const mockFetch = vi.fn().mockResolvedValue({
      ok: true,
      json: async () => ({
        candidates: [
          {
            content: {
              parts: [{ text: 'Tailored resume content from Gemini 2.0 Flash' }],
            },
          },
        ],
        usageMetadata: { totalTokenCount: 520 },
      }),
    });

    const res = await callLLM({
      userPrompt: 'Tailor resume for Senior DevOps role',
      fetchFn: mockFetch as any,
    });

    expect(mockFetch).toHaveBeenCalled();
    const calledUrl = mockFetch.mock.calls[0][0];
    expect(calledUrl).toContain('generativelanguage.googleapis.com');
    expect(calledUrl).toContain('key=test-gemini-key-123');
    expect(res.provider).toBe('gemini');
    expect(res.content).toBe('Tailored resume content from Gemini 2.0 Flash');
    expect(res.tokensUsed).toBe(520);
  });

  it('Test 5: Cascades to Groq when Gemini fails with error', async () => {
    process.env['GEMINI_API_KEY'] = 'failing-gemini-key';
    process.env['GROQ_API_KEY'] = 'working-groq-key';

    const mockFetch = vi.fn().mockImplementation(async (url: string) => {
      if (url.includes('generativelanguage.googleapis.com')) {
        return {
          ok: false,
          status: 500,
          text: async () => 'Internal Server Error in Gemini',
        };
      }
      if (url.includes('api.groq.com')) {
        return {
          ok: true,
          json: async () => ({
            choices: [
              {
                message: { content: 'Content generated by Groq Llama 3.3' },
              },
            ],
            usage: { total_tokens: 410 },
          }),
        };
      }
      return { ok: false, status: 404 };
    });

    const res = await callLLM({
      userPrompt: 'Generate tailored CV',
      fetchFn: mockFetch as any,
    });

    expect(res.provider).toBe('groq');
    expect(res.content).toBe('Content generated by Groq Llama 3.3');
    expect(res.tokensUsed).toBe(410);
  });

  it('Test 6: PDF Generator generates valid ATS-formatted resume document', () => {
    const sampleResume: ResumeData = {
      atsScore: 95,
      candidate: {
        name: 'Taylor Swift',
        email: 'taylor@example.com',
        phone: '123-456-7890',
        location: 'New York, NY',
      },
      summary: 'Experienced developer with strong background.',
      experience: [
        {
          role: 'Lead Architect',
          company: 'Acme Inc',
          location: 'Remote',
          period: '2021 - Present',
          highlights: ['Improved latency by 50%', 'Managed team of 8'],
        },
      ],
      skills: {
        languages: ['TypeScript', 'Python'],
        frameworks: ['React', 'Next.js'],
      },
      education: [
        {
          degree: 'B.S. in Computer Science',
          institution: 'MIT',
          year: '2019',
        },
      ],
    };

    const doc = generateResumePdf(sampleResume);
    expect(doc).toBeDefined();
    expect(doc.internal.pages.length).toBeGreaterThan(0);
  });

  it('Test 7: PDF Generator generates valid executive Cover Letter document', () => {
    const doc = generateCoverLetterPdf(
      'Paragraph 1 of cover letter.\n\nParagraph 2 of cover letter.',
      { name: 'Jordan Vance', email: 'jordan@example.com' }
    );
    expect(doc).toBeDefined();
    expect(doc.internal.pages.length).toBeGreaterThan(0);
  });
});
