import type { OnboardSourceInput } from '../onboarding.js';

export const INITIAL_COMPANY_CATALOG: OnboardSourceInput[] = [
  {
    companyName: 'Stripe',
    companyDomain: 'stripe.com',
    careersUrl: 'https://stripe.com/careers',
    atsType: 'greenhouse',
    boardIdentifier: 'stripe',
    sourceUrl: 'https://boards.greenhouse.io/stripe',
    priority: 10,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'Figma',
    companyDomain: 'figma.com',
    careersUrl: 'https://figma.com/careers',
    atsType: 'lever',
    boardIdentifier: 'figma',
    sourceUrl: 'https://jobs.lever.co/figma',
    priority: 10,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'Linear',
    companyDomain: 'linear.app',
    careersUrl: 'https://linear.app/careers',
    atsType: 'ashby',
    boardIdentifier: 'linear',
    sourceUrl: 'https://jobs.ashbyhq.com/linear',
    priority: 10,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'OpenAI',
    companyDomain: 'openai.com',
    careersUrl: 'https://openai.com/careers',
    atsType: 'ashby',
    boardIdentifier: 'openai',
    sourceUrl: 'https://jobs.ashbyhq.com/openai',
    priority: 20,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'Anthropic',
    companyDomain: 'anthropic.com',
    careersUrl: 'https://anthropic.com/careers',
    atsType: 'greenhouse',
    boardIdentifier: 'anthropic',
    sourceUrl: 'https://boards.greenhouse.io/anthropic',
    priority: 20,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'Retool',
    companyDomain: 'retool.com',
    careersUrl: 'https://retool.com/careers',
    atsType: 'greenhouse',
    boardIdentifier: 'retool',
    sourceUrl: 'https://boards.greenhouse.io/retool',
    priority: 30,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
  {
    companyName: 'Supabase',
    companyDomain: 'supabase.com',
    careersUrl: 'https://supabase.com/careers',
    atsType: 'greenhouse',
    boardIdentifier: 'supabase',
    sourceUrl: 'https://boards.greenhouse.io/supabase',
    priority: 30,
    scheduleIntervalMinutes: 360,
    isActive: true,
  },
];
